export const dbSchemaForUi = {
  relations: [
    {
      fromTable: 'all_inventory_count',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'all_inventory_count',
      fromColumn: 'taskTypeId',
      toTable: 'task_type',
      toColumn: 'id',
    },
    {
      fromTable: 'all_inventory_count',
      fromColumn: 'taskStatusId',
      toTable: 'task_status',
      toColumn: 'id',
    },
    {
      fromTable: 'all_inventory_count',
      fromColumn: 'userId',
      toTable: 'user',
      toColumn: 'id',
    },
    {
      fromTable: 'all_rma',
      fromColumn: 'taskStatusId',
      toTable: 'task_status',
      toColumn: 'id',
    },
    {
      fromTable: 'all_rma',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'all_rma',
      fromColumn: 'userId',
      toTable: 'user',
      toColumn: 'id',
    },
    {
      fromTable: 'boxsize',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'company',
      fromColumn: 'companySettingId',
      toTable: 'company_setting',
      toColumn: 'id',
    },
    {
      fromTable: 'cylinder',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'order',
      fromColumn: 'comapnyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'order',
      fromColumn: 'taskStatusId',
      toTable: 'task_status',
      toColumn: 'id',
    },
    {
      fromTable: 'order',
      fromColumn: 'roleId',
      toTable: 'role',
      toColumn: 'id',
    },
    {
      fromTable: 'order',
      fromColumn: 'userId',
      toTable: 'user',
      toColumn: 'id',
    },
    {
      fromTable: 'order_basket',
      fromColumn: 'orderId',
      toTable: 'order',
      toColumn: 'id',
    },
    {
      fromTable: 'order_boxes',
      fromColumn: 'boxSizeId',
      toTable: 'boxsize',
      toColumn: 'id',
    },
    {
      fromTable: 'order_boxes',
      fromColumn: 'orderId',
      toTable: 'order',
      toColumn: 'id',
    },
    {
      fromTable: 'order_boxes_items',
      fromColumn: 'orderBoxesId',
      toTable: 'order_boxes',
      toColumn: 'id',
    },
    {
      fromTable: 'order_line',
      fromColumn: 'orderId',
      toTable: 'order',
      toColumn: 'id',
    },
    {
      fromTable: 'order_line',
      fromColumn: 'taskStatusId',
      toTable: 'task_status',
      toColumn: 'id',
    },
    {
      fromTable: 'partcqaunt',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'priorityproducts',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'priorityproductshierarchy',
      fromColumn: 'PART',
      toTable: 'priorityproducts',
      toColumn: 'PART',
    },
    {
      fromTable: 'priorityproductshierarchy',
      fromColumn: 'companyId',
      toTable: 'priorityproducts',
      toColumn: 'companyId',
    },
    {
      fromTable: 'priorityproductshierarchy',
      fromColumn: 'SON',
      toTable: 'priorityproducts',
      toColumn: 'PART',
    },
    {
      fromTable: 'priorityproductshierarchy',
      fromColumn: 'companyId',
      toTable: 'priorityproducts',
      toColumn: 'companyId',
    },
    {
      fromTable: 'priorityproductslocation',
      fromColumn: 'zoneId',
      toTable: 'zone',
      toColumn: 'id',
    },
    {
      fromTable: 'priorityproductslocation',
      fromColumn: 'priorityProductsId',
      toTable: 'priorityproducts',
      toColumn: 'id',
    },
    {
      fromTable: 'shipment_priority',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'task_grv',
      fromColumn: 'allGrvId',
      toTable: 'all_grv',
      toColumn: 'id',
    },
    {
      fromTable: 'task_inventory_count',
      fromColumn: 'allInventoryCountId',
      toTable: 'all_inventory_count',
      toColumn: 'id',
    },
    {
      fromTable: 'task_rma',
      fromColumn: 'allRmaId',
      toTable: 'all_rma',
      toColumn: 'id',
    },
    {
      fromTable: 'task_user',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'task_user',
      fromColumn: 'userId',
      toTable: 'user',
      toColumn: 'id',
    },
    {
      fromTable: 'task_user',
      fromColumn: 'taskStatusId',
      toTable: 'task_status',
      toColumn: 'id',
    },
    {
      fromTable: 'task_user',
      fromColumn: 'taskTypeId',
      toTable: 'task_type',
      toColumn: 'id',
    },
    {
      fromTable: 'user_company',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
    {
      fromTable: 'user_company',
      fromColumn: 'usersId',
      toTable: 'user',
      toColumn: 'id',
    },
    {
      fromTable: 'users_roles',
      fromColumn: 'roleId',
      toTable: 'role',
      toColumn: 'id',
    },
    {
      fromTable: 'users_roles',
      fromColumn: 'usersId',
      toTable: 'user',
      toColumn: 'id',
    },
    {
      fromTable: 'zone',
      fromColumn: 'companyId',
      toTable: 'company',
      toColumn: 'id',
    },
  ],
  tables: [
    {
      table: 'all_grv',
      fields: [
        'updatedBy',
        'id',
        'DataInfo',
        'PartNumber',
        'QTYtoassemble',
        'QTYassembled',
        'Total',
        'Supplier',
        'PalletNumber',
        'PO',
        'taskInfo',
        'Location',
        'NoOfBoxes',
        'NoOfItems',
        'orderName',
        'remarks',
        'bulkQauntity',
        'orderid',
        'orderlineId',
        'taskPriority',
        'rmaNumber',
        'trackingNumber',
        'statusRma',
        'customerName',
        'cylinder',
        'backToInventory',
        'taskTypeId',
        'userId',
        'taskStatusId',
        'companyId',
        'productName',
        'productDescription',
        'CURDATE',
      ],
    },
    {
      table: 'all_inventory_count',
      fields: [
        'updatedBy',
        'id',
        'DataInfo',
        'PartNumber',
        'QTYtoassemble',
        'QTYassembled',
        'Total',
        'BIN',
        'QTY',
        'BIN_1',
        'QTY_1',
        'BIN_2',
        'QTY_2',
        'Supplier',
        'PalletNumber',
        'PO',
        'taskInfo',
        'Location',
        'NoOfBoxes',
        'NoOfItems',
        'orderName',
        'remarks',
        'bulkQauntity',
        'orderid',
        'orderlineId',
        'taskPriority',
        'rmaNumber',
        'trackingNumber',
        'statusRma',
        'customerName',
        'cylinder',
        'backToInventory',
        'taskTypeId',
        'userId',
        'taskStatusId',
        'companyId',
        'productName',
        'productDescription',
      ],
    },
    {
      table: 'all_rma',
      fields: [
        'updatedBy',
        'id',
        'CUSTNAME',
        'CUSTDES',
        'CURDATE',
        'DOCNO',
        'DETAILS',
        'STATDES',
        'FBCM_RETREASONCODE',
        'FBCM_RETREASONDES',
        'Title',
        'trackingNumber',
        'taskPriority',
        'remarks',
        'userId',
        'companyId',
        'taskStatusId',
      ],
    },
    {
      table: 'boxsize',
      fields: ['updatedBy', 'id', 'sizeDesc', 'companyId'],
    },

    {
      table: 'order',
      fields: [
        'id',
        'CUSTNAME',
        'CUSTNO',
        'ORDNAME',
        'STCODE',
        'STDES',
        'ADDRESS',
        'ADDRESS2',
        'ADDRESS3',
        'STATE',
        'STATECODE',
        'STATENAME',
        'CURDATE',
        'ZIP',
        'COUNTRYNAME',
        'ordertext',
        'orderRemarks',
        'priorityOrder',
        'shipmentOrder',
        'DETAILS',
        'ShData',
        'CUSTDES',
        'NAME',
        'PHONENUM',
        'FAX',
        'trackingNumber',
        'shipRushStatus',
        'shipRushDeliveryId',
        'DOCUMENT_DOCNO',
        'DOCUMENT_DOC',
        'shipRushShipmentId',
        'accountId',
        'accountZip',
        'orderNote',
        'Pallet',
        'userId',
        'taskStatusId',
        'roleId',
        'comapnyId',
        'CustomerPO',
      ],
    },

    {
      table: 'order_boxes',
      fields: [
        'id',
        'lineRemarks',
        'boxweight',
        'boxNo',
        'boxSizeId',
        'orderId',
        'itemsCount',
        'updatedBy',
      ],
    },
    {
      table: 'order_boxes_items',
      fields: [
        'id',
        'partNumber',
        'productName',
        'productDescription',
        'itemsCount',
        'orderId',
        'orderBoxesId',
        'updatedBy',
        'orderLineItemsCount',
      ],
    },
    {
      table: 'order_line',
      fields: [
        'id',
        'PARTNAME',
        'PARTDES',
        'TBALANCE',
        'Fullfilled',
        'FullfilledSuperViser',
        'BARCODE',
        'lineRemarks',
        'approved',
        'picked',
        'pickingError',
        'prioritykline',
        'priorityremarks',
        'pickingAid',
        'assemblyAid',
        'ORDI',
        'orderId',
        'taskStatusId',
      ],
    },
    {
      table: 'orderhist',
      fields: [
        'id',
        'CUSTNAME',
        'CUSTNO',
        'ORDNAME',
        'STCODE',
        'STDES',
        'ADDRESS',
        'ADDRESS2',
        'ADDRESS3',
        'STATE',
        'STATECODE',
        'STATENAME',
        'CURDATE',
        'ZIP',
        'COUNTRYNAME',
        'ordertext',
        'orderRemarks',
        'priorityOrder',
        'shipmentOrder',
        'DETAILS',
        'ShData',
        'CUSTDES',
        'NAME',
        'PHONENUM',
        'FAX',
        'trackingNumber',
        'shipRushStatus',
        'shipRushDeliveryId',
        'DOCUMENT_DOCNO',
        'DOCUMENT_DOC',
        'shipRushShipmentId',
        'accountId',
        'accountZip',
        'orderNote',
        'Pallet',
        'userId',
        'taskStatusId',
        'roleId',
        'comapnyId',
        'orgId',
      ],
    },
    {
      table: 'priorityproducts',
      fields: [
        'id',
        'PARTNAME',
        'TYPE',
        'BARCODE',
        'PART',
        'PARTDES',
        'companyId',
        'STATDES',
      ],
    },
    {
      table: 'priorityproductshierarchy',
      fields: ['id', 'PART', 'SON', 'companyId'],
    },
    {
      table: 'priorityproductslocation',
      fields: [
        'id',
        'location',
        'stockDate',
        'quantity',
        'priorityProductsId',
        'zoneId',
        'remarks',
      ],
    },
    {
      table: 'product_status',
      fields: ['updatedBy', 'id', 'productStatus', 'companyId'],
    },

    {
      table: 'role',
      fields: ['updatedBy', 'id', 'role', 'roleDisplayName', 'color'],
    },

    {
      table: 'task_grv',
      fields: [
        'updatedBy',
        'id',
        'PartNumber',
        'NoOfBoxes_0',
        'NoOfItems_0',
        'NoOfBoxes_1',
        'NoOfItems_1',
        'NoOfBoxes_2',
        'NoOfItems_2',
        'NoOfBoxes_3',
        'NoOfItems_3',
        'NoOfBoxes_4',
        'NoOfItems_4',
        'NoOfBoxes_5',
        'NoOfItems_5',
        'bulkQauntity',
        'Total',
        'allGrvId',
        'DataInfo',
        'productName',
        'productDescription',
        'quantityRequired',
        'task_grvcol',
      ],
    },
    {
      table: 'task_inventory_count',
      fields: [
        'updatedBy',
        'id',
        'DataInfo',
        'PartNumber',
        'NoOfBoxes_0',
        'NoOfItems_0',
        'NoOfBoxes_1',
        'NoOfItems_1',
        'NoOfBoxes_2',
        'NoOfItems_2',
        'NoOfBoxes_3',
        'NoOfItems_3',
        'NoOfBoxes_4',
        'NoOfItems_4',
        'NoOfBoxes_5',
        'NoOfItems_5',
        'bulkQauntity',
        'Total',
        'allInventoryCountId',
        'productName',
        'productDescription',
        'location',
      ],
    },
    {
      table: 'task_rma',
      fields: [
        'updatedBy',
        'id',
        'PartNumber',
        'partQount',
        'backToInventory',
        'productStatus',
        'cylinder',
        'remarks',
        'allRmaId',
        'productName',
        'productDescription',
      ],
    },
    {
      table: 'task_status',
      fields: ['updatedBy', 'id', 'status', 'color'],
    },
    {
      table: 'task_type',
      fields: ['updatedBy', 'id', 'role'],
    },
    {
      table: 'task_user',
      fields: [
        'updatedBy',
        'id',
        'DataInfo',
        'PartNumber',
        'QTYtoassemble',
        'QTYassembled',
        'Total',
        'BIN',
        'QTY',
        'BIN_1',
        'QTY_1',
        'BIN_2',
        'QTY_2',
        'Supplier',
        'PalletNumber',
        'PO',
        'taskInfo',
        'Location',
        'NoOfBoxes',
        'NoOfItems',
        'orderName',
        'remarks',
        'bulkQauntity',
        'orderid',
        'orderlineId',
        'taskPriority',
        'rmaNumber',
        'trackingNumber',
        'pictureOne',
        'pictureTwo',
        'statusRma',
        'customerName',
        'cylinder',
        'backToInventory',
        'taskTypeId',
        'userId',
        'taskStatusId',
        'companyId',
        'productName',
        'productDescription',
      ],
    },

    {
      table: 'user',
      fields: [
        'updatedBy',
        'id',
        'userName',
        'userSurname',
        'userUuid',
        'userMail',
        'userMobile',
        'color',
        'userPasswordEnc',
        'selectedCompany',
        'otp',
      ],
    },
    {
      table: 'user_company',
      fields: ['updatedBy', 'id', 'usersId', 'companyId'],
    },
    {
      table: 'users_roles',
      fields: ['updatedBy', 'id', 'usersId', 'roleId'],
    },
    {
      table: 'zone',
      fields: ['updatedBy', 'id', 'zoneName', 'color', 'priority', 'companyId'],
    },
  ],
};
